// <auto-generated />

using System;
using Database.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Database.EFCore.Migrations
{
    [DbContext(typeof(ExampleContext))]
    partial class ExampleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Database.EFCore.Entities.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy",
                        NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("Name")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("User");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Name = "Freezing"
                    },
                    new
                    {
                        Id = 2,
                        Name = "Nasty"
                    },
                    new
                    {
                        Id = 3,
                        Name = "Oleg"
                    },
                    new
                    {
                        Id = 4,
                        Name = "Vlad"
                    },
                    new
                    {
                        Id = 5,
                        Name = "Kostya"
                    }
                );
            });

            modelBuilder.Entity("Database.EFCore.Entities.News", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy",
                        NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<int?>("UserId")
                    .HasColumnType("integer");

                b.Property<decimal>("Title")
                    .HasColumnType("string");

                b.Property<DateTime>("TimeStamp")
                    .HasColumnType("timestamp without time zone");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("News");

                b.HasData(
                    new
                    {
                        Id = 1,
                        UserId = 3,
                        Title = "First title",
                        TimeStamp = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                    },
                    new
                    {
                        Id = 2,
                        UserId = 5,
                        Title = "Second title",
                        Temperature = 5.1m,
                        TimeStamp = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                    });
            });

            modelBuilder.Entity("Database.EFCore.Entities.News", b =>
            {
                b.HasOne("Database.EFCore.Entities.User", "User")
                    .WithMany()
                    .HasForeignKey("UserId");
            });
#pragma warning restore 612, 618
        }
    }
}